"""TAE CLI-1 — command dispatcher."""

from __future__ import annotations

import sys

from tae_cli.commands import (
    adaptive_weights,
    adaptive_deployment,
    dpe_adaptive,
    dpe_collaborative,
    dpe_competitive,
    dpe_evaluator,
    dpe_learning,
    dpe_events,
    dpe_splitter,
    decision_state,
    executive_review,
    exit_strategy_comparison,
    exit_replay_horizon_audit,
    final_check,
    full_paper_cycle,
    growth_analytics,
    growth_intelligence,
    health,
    help as help_cmd,
    historical_refresh,
    learning_profit,
    learning_economic_ablation,
    learning_attribution,
    learning_runtime,
    investment_council,
    conflict_resolution,
    long_term_learning,
    morning_audit,
    opportunity,
    outcome_memory,
    paper_experiments,
    paper_decisions,
    paper_execution,
    paper_mark_to_market,
    parallel_paper,
    strategy_lab,
    today,
    canonical_vs_paper,
    paper_cycle_retest,
    paper_validation_30d,
    philosophy,
    philosophy_performance,
    policy,
    portfolio_protect,
    profit_pipeline,
    profit_optimization,
    conversion_breakthrough,
    opportunity_attrition,
    profit_targets,
    promotion_lock,
    protect,
    research,
    recovery,
    self_improve,
    migration,
    status,
    strategy_survival,
    winner,
    mark_diagnostic,
    test_suite,
)

COMMANDS = {
    "full-paper-cycle": full_paper_cycle.run,
    "historical-refresh": historical_refresh.run,
    "outcome-memory": outcome_memory.run,
    "strategy-survival": strategy_survival.run,
    "long-term-learning": long_term_learning.run,
    "philosophy-performance": philosophy_performance.run,
    "adaptive-weights": adaptive_weights.run,
    "adaptive-deployment": adaptive_deployment.run,
    "paper-cycle-retest": paper_cycle_retest.run,
    "30-day-paper-validation": paper_validation_30d.run,
    "promotion-lock": promotion_lock.run,
    "health": health.run,
    "final-check": final_check.run,
    "test": test_suite.run,
    "protect": protect.run,
    "portfolio-protect": portfolio_protect.run,
    "policy": policy.run,
    "growth-analytics": growth_analytics.run,
    "opportunity": opportunity.run,
    "winner": winner.run,
    "growth-intelligence": growth_intelligence.run,
    "profit-targets": profit_targets.run,
    "profit-pipeline": profit_pipeline.run,
    "profit-optimization": profit_optimization.run,
    "conversion-breakthrough": conversion_breakthrough.run,
    "opportunity-attrition": opportunity_attrition.run,
    "philosophy": philosophy.run,
    "dpe-events": dpe_events.run,
    "dpe-splitter": dpe_splitter.run,
    "dpe-competitive": dpe_competitive.run,
    "dpe-collaborative": dpe_collaborative.run,
    "dpe-evaluator": dpe_evaluator.run,
    "dpe-learning": dpe_learning.run,
    "dpe-adaptive": dpe_adaptive.run,
    "learning-profit": learning_profit.run,
    "learning-economic-ablation": learning_economic_ablation.run,
    "learning-attribution-run": learning_attribution.run_run,
    "learning-attribution-status": learning_attribution.run_status,
    "learning-attribution-report": learning_attribution.run_report,
    "learning-attribution-verify": learning_attribution.run_verify,
    "learning-runtime-start": learning_runtime.run_start,
    "learning-runtime-stop": learning_runtime.run_stop,
    "learning-runtime-status": learning_runtime.run_status,
    "learning-runtime-cycle": learning_runtime.run_cycle,
    "learning-runtime-health": learning_runtime.run_health,
    "learning-runtime-autostart-install": learning_runtime.run_autostart_install,
    "learning-runtime-autostart-status": learning_runtime.run_autostart_status,
    "learning-runtime-autostart-remove": learning_runtime.run_autostart_remove,
    "decision-state-refresh": decision_state.run,
    "executive-review": executive_review.run,
    "exit-strategy-comparison": exit_strategy_comparison.run,
    "exit-replay-horizon-audit": exit_replay_horizon_audit.run,
    "conflict-resolution-refresh": conflict_resolution.run,
    "paper-experiments": paper_experiments.run,
    "paper-decisions": paper_decisions.run,
    "paper-execution": paper_execution.run,
    "paper-mark-to-market": paper_mark_to_market.run,
    "parallel-paper-start": parallel_paper.run_start,
    "parallel-paper-run-once": parallel_paper.run_once,
    "parallel-paper-health": parallel_paper.run_health,
    "parallel-paper-report": parallel_paper.run_report,
    "parallel-paper-stop": parallel_paper.run_stop,
    "parallel-paper-cycle": parallel_paper.run_cycle_cmd,
    "parallel-paper-autostart-install": parallel_paper.run_autostart_install,
    "parallel-paper-autostart-status": parallel_paper.run_autostart_status,
    "parallel-paper-autostart-remove": parallel_paper.run_autostart_remove,
    "strategy-lab": strategy_lab.run,
    "strategy-lab-status": strategy_lab.run_status,
    "strategy-lab-scoreboard": strategy_lab.run_scoreboard,
    "strategy-lab-explain": strategy_lab.run_explain,
    "strategy-lab-health": strategy_lab.run_health,
    "strategy-lab-research": strategy_lab.run_research,
    "strategy-lab-metrics": strategy_lab.run_metrics,
    "strategy-lab-recommend": strategy_lab.run_recommend,
    "strategy-lab-promotion": strategy_lab.run_promotion,
    "today": today.run,
    "canonical-vs-paper": canonical_vs_paper.run,
    "morning-audit": morning_audit.run,
    "investment-council": investment_council.run,
    "research": research.run,
    "migration": migration.run,
    "recovery": recovery.run,
    "self-improve": self_improve.run,
    "status": status.run,
    "help": help_cmd.run,
    "market-mark-diagnostic": mark_diagnostic.run,
}


def main(argv: list[str] | None = None) -> int:
    args = list(argv if argv is not None else sys.argv[1:])
    command = args[0].lower() if args else "help"
    handler = COMMANDS.get(command)
    if handler is None:
        print(f"Unknown command: {command}", file=sys.stderr)
        help_cmd.run([])
        return 2
    return int(handler(args[1:]))
