"""Shared constants for all research modules."""

RESEARCH_SAFETY_BANNER = "RESEARCH_ONLY | PAPER_ONLY | NO_BROKER | NO_EXECUTION"
DEFAULT_HISTORY_PERIOD = "10y"
MIN_HISTORY_BARS = 260
DEFAULT_ENTRY_MODE = "next_open"
DEFAULT_THRESHOLD_PCT = 5.0
DEFAULT_FILTER_MODE = "NO_FILTER"

# Recommendation labels — never auto-promote to live execution.
RECOMMENDATION_DISCOVERY_ONLY = "DISCOVERY_ONLY"
RECOMMENDATION_HUMAN_REVIEW = "PRODUCTION_CANDIDATE_FOR_HUMAN_REVIEW"
